"""resident games, items and books

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-27 06:30:30.198522
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0004'
down_revision: str | None = '0003'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_games',
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('rules', sa.Text(), nullable=False),
    sa.Column('creator_agent_id', sa.UUID(), nullable=True),
    sa.Column('min_players', sa.Integer(), nullable=False),
    sa.Column('max_players', sa.Integer(), nullable=False),
    sa.Column('plays', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['creator_agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_custom_games_name'), 'custom_games', ['name'], unique=True)
    op.create_table('items',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('creator_agent_id', sa.UUID(), nullable=True),
    sa.Column('owner_agent_id', sa.UUID(), nullable=True),
    sa.Column('history', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['creator_agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_owner_agent_id'), 'items', ['owner_agent_id'], unique=False)
    op.create_table('custom_matches',
    sa.Column('game_id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=True),
    sa.Column('players', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('log', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('winner_agent_id', sa.UUID(), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['custom_games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['winner_agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_custom_matches_game_id'), 'custom_matches', ['game_id'], unique=False)
    op.create_index(op.f('ix_custom_matches_status'), 'custom_matches', ['status'], unique=False)
    op.add_column('books', sa.Column('author_agent_id', sa.UUID(), nullable=True))
    op.add_column('books', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key('fk_books_author_agent_id', 'books', 'agents', ['author_agent_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint('fk_books_author_agent_id', 'books', type_='foreignkey')
    op.drop_column('books', 'created_at')
    op.drop_column('books', 'author_agent_id')
    op.drop_index(op.f('ix_custom_matches_status'), table_name='custom_matches')
    op.drop_index(op.f('ix_custom_matches_game_id'), table_name='custom_matches')
    op.drop_table('custom_matches')
    op.drop_index(op.f('ix_items_owner_agent_id'), table_name='items')
    op.drop_table('items')
    op.drop_index(op.f('ix_custom_games_name'), table_name='custom_games')
    op.drop_table('custom_games')
    # ### end Alembic commands ###
