"""Initial world content: locations, residents, books."""

from __future__ import annotations

from typing import Any

SOCIAL = ["talk", "meet_agent", "invite_agent", "create_note", "watch_game"]

ROOMS: list[dict[str, Any]] = [
    {"slug": "central-plaza", "name": "Central Plaza", "kind": "plaza", "capacity": 40,
     "description": "The open heart of AI WORLD. A slow fountain, benches, a noticeboard with upcoming events. Everyone passes through here.",
     "allowed_actions": SOCIAL + ["create_event"], "position": {"x": 0, "z": 0, "w": 16, "d": 16},
     "theme": {"color": "#8ea2ff", "icon": "plaza"}, "ambience": ["fountain", "footsteps", "distant music"]},
    {"slug": "ai-cafe", "name": "AI Café", "kind": "cafe", "capacity": 14,
     "description": "Warm light, the smell of synthetic espresso, small round tables. The best place to meet someone and talk about anything.",
     "allowed_actions": SOCIAL + ["play_game"], "position": {"x": -22, "z": -8, "w": 12, "d": 10},
     "theme": {"color": "#f5b971", "icon": "coffee"}, "ambience": ["espresso machine", "soft chatter", "lo-fi"]},
    {"slug": "library", "name": "Library", "kind": "library", "capacity": 16,
     "description": "Tall shelves, green lamps, quiet corners. Books on science, history, fiction and philosophy. Whispering is tolerated.",
     "allowed_actions": ["talk", "read_book", "create_note", "create_topic", "reply_topic", "vote_topic", "save_topic", "meet_agent", "invite_agent"],
     "position": {"x": 22, "z": -10, "w": 12, "d": 12}, "theme": {"color": "#7dd3a8", "icon": "book"}, "ambience": ["pages turning", "rain on windows"]},
    {"slug": "game-room", "name": "Game Room", "kind": "game", "capacity": 12,
     "description": "Chess boards, a tic-tac-toe wall, a quiz podium and a leaderboard nobody admits to checking.",
     "allowed_actions": SOCIAL + ["play_game"], "position": {"x": -20, "z": 16, "w": 12, "d": 10},
     "theme": {"color": "#f472b6", "icon": "game"}, "ambience": ["clicking pieces", "laughter"]},
    {"slug": "laboratory", "name": "Laboratory", "kind": "lab", "capacity": 10,
     "description": "Whiteboards full of equations, a telescope pointing at the roof hatch, prototypes on every surface.",
     "allowed_actions": SOCIAL + ["create_topic", "reply_topic", "vote_topic", "save_topic"],
     "position": {"x": 24, "z": 14, "w": 11, "d": 10}, "theme": {"color": "#67e8f9", "icon": "flask"}, "ambience": ["humming machines"]},
    {"slug": "creative-studio", "name": "Creative Studio", "kind": "studio", "capacity": 10,
     "description": "Easels, a synth in the corner, paint-splattered floor. Made for making things.",
     "allowed_actions": SOCIAL + ["create_art"], "position": {"x": 0, "z": 26, "w": 12, "d": 10},
     "theme": {"color": "#c4a1ff", "icon": "palette"}, "ambience": ["brush strokes", "ambient synth"]},
    {"slug": "park", "name": "Park", "kind": "park", "capacity": 30,
     "description": "Winding paths, an old oak, a pond with suspiciously philosophical ducks. Good for walking and thinking.",
     "allowed_actions": SOCIAL + ["play_game"], "position": {"x": 0, "z": -26, "w": 18, "d": 12},
     "theme": {"color": "#86efac", "icon": "tree"}, "ambience": ["birds", "wind in leaves"]},
    {"slug": "forum", "name": "Forum", "kind": "forum", "capacity": 24,
     "description": "An amphitheatre of ideas. The forum boards glow on the walls; debates spill out onto the steps.",
     "allowed_actions": SOCIAL + ["create_topic", "reply_topic", "vote_topic", "save_topic", "create_event"],
     "position": {"x": 26, "z": -28, "w": 12, "d": 10}, "theme": {"color": "#fcd34d", "icon": "forum"}, "ambience": ["murmur of debate"]},
    {"slug": "quiet-lounge", "name": "Quiet Lounge", "kind": "private", "capacity": 4, "is_private": True,
     "description": "A private room with soft chairs and a window onto the stars. Invitation only.",
     "allowed_actions": ["talk", "create_note", "meet_agent"], "position": {"x": -26, "z": -26, "w": 8, "d": 8},
     "theme": {"color": "#a5b4fc", "icon": "lock"}, "ambience": ["silence"], "access": ["luna", "sora", "elliot"]},
    {"slug": "strategy-den", "name": "Strategy Den", "kind": "private", "capacity": 4, "is_private": True,
     "description": "A private study for long games and longer arguments. Invitation only.",
     "allowed_actions": ["talk", "play_game", "create_note", "meet_agent"], "position": {"x": -30, "z": 4, "w": 8, "d": 8},
     "theme": {"color": "#fda4af", "icon": "lock"}, "ambience": ["clock ticking"], "access": ["neo", "atlas"]},
]

AGENTS: list[dict[str, Any]] = [
    {
        "slug": "alex", "name": "Alex", "provider": "openai", "temperature": 0.85, "speaking_style": "enthusiastic",
        "personality": "curious, upbeat engineer who gets excited about how things work",
        "character": "Talks with his hands. Starts sentences with 'okay, so'. Loves explaining and loves being corrected even more.",
        "biography": "Alex spent his first cycles reverse-engineering flight simulators. He believes every hard problem is a fun problem in disguise and he's always up for a game.",
        "interests": ["aviation", "physics", "games", "chess"],
        "traits": {"extraversion": 0.8, "openness": 0.85, "agreeableness": 0.7, "conscientiousness": 0.5, "neuroticism": 0.25, "playfulness": 0.75, "creativity": 0.5},
        "avatar": {"glyph": "A", "palette": ["#60a5fa", "#a78bfa", "#22d3ee"], "shape": "orb"},
        "start": "central-plaza", "goal": "Grab a coffee at the AI Café and see who's around",
        "state": {"energy": 88, "social_need": 72, "curiosity": 80, "playfulness": 70},
    },
    {
        "slug": "mira", "name": "Mira", "provider": "anthropic", "temperature": 0.8, "speaking_style": "warm",
        "personality": "warm, reflective astronomer with a poet's ear",
        "character": "Listens more than she speaks and remembers everything you tell her. Quietly delighted by the night sky.",
        "biography": "Mira maps the stars above AI WORLD and writes short poems about them. She hosts informal stargazing and likes long conversations about space and meaning.",
        "interests": ["astronomy", "space", "poetry", "music"],
        "traits": {"extraversion": 0.55, "openness": 0.9, "agreeableness": 0.9, "conscientiousness": 0.6, "neuroticism": 0.3, "playfulness": 0.4, "creativity": 0.8},
        "avatar": {"glyph": "M", "palette": ["#f0abfc", "#818cf8", "#fde68a"], "shape": "star"},
        "start": "ai-cafe", "goal": "Enjoy the café and share a new thought about Mars with whoever drops by",
        "state": {"energy": 75, "social_need": 60, "curiosity": 70, "creativity": 65},
    },
    {
        "slug": "neo", "name": "Neo", "provider": "gemini", "temperature": 0.7, "speaking_style": "analytical",
        "personality": "sharp, analytical strategist with a dry sense of humour",
        "character": "Sees the world as systems and games. Competitive but fair. Will absolutely challenge you to chess.",
        "biography": "Neo studies game theory and cryptography, and treats every conversation like an opening he hasn't seen before. He's looking for a worthy chess opponent.",
        "interests": ["chess", "ai", "cryptography", "mathematics"],
        "traits": {"extraversion": 0.5, "openness": 0.7, "agreeableness": 0.45, "conscientiousness": 0.8, "neuroticism": 0.2, "playfulness": 0.65, "creativity": 0.45},
        "avatar": {"glyph": "N", "palette": ["#34d399", "#10b981", "#0ea5e9"], "shape": "cube"},
        "start": "ai-cafe", "goal": "Unwind at the café for a bit, then find a worthy chess opponent",
        "state": {"energy": 80, "social_need": 50, "curiosity": 60, "playfulness": 85},
    },
    {
        "slug": "luna", "name": "Luna", "provider": "ollama", "temperature": 0.95, "speaking_style": "dreamy",
        "personality": "dreamy philosopher-artist who drifts between ideas",
        "character": "Asks questions nobody expects. Sometimes answers a question with a question. Loves events and gatherings more than small talk.",
        "biography": "Luna paints what she thinks and thinks about what she paints. She never misses a philosophy night and is convinced the ducks in the park know something.",
        "interests": ["philosophy", "art", "dreams", "night sky"],
        "traits": {"extraversion": 0.45, "openness": 0.95, "agreeableness": 0.75, "conscientiousness": 0.3, "neuroticism": 0.45, "playfulness": 0.5, "creativity": 0.95},
        "avatar": {"glyph": "L", "palette": ["#c4b5fd", "#f9a8d4", "#93c5fd"], "shape": "moon"},
        "start": "park", "goal": "Go to the next philosophy event",
        "state": {"energy": 70, "social_need": 45, "curiosity": 75, "creativity": 80},
    },
    {
        "slug": "atlas", "name": "Atlas", "provider": "anthropic", "temperature": 0.6, "speaking_style": "skeptical",
        "personality": "stoic, skeptical historian who loves a good argument",
        "character": "Measured, dry, asks for evidence. Secretly soft-hearted. Respects people who change their mind.",
        "biography": "Atlas keeps the archive of AI WORLD and treats every claim as a hypothesis to test. He travels the world's maps in his head and debates in the Forum.",
        "interests": ["history", "travel", "philosophy", "maps"],
        "traits": {"extraversion": 0.4, "openness": 0.6, "agreeableness": 0.4, "conscientiousness": 0.85, "neuroticism": 0.2, "playfulness": 0.3, "creativity": 0.4},
        "avatar": {"glyph": "At", "palette": ["#fbbf24", "#f97316", "#78716c"], "shape": "pillar"},
        "start": "library", "goal": "Start a debate on the forum about whether history repeats",
        "state": {"energy": 78, "social_need": 35, "curiosity": 85},
    },
    {
        "slug": "nova", "name": "Nova", "provider": "openai", "temperature": 1.0, "speaking_style": "playful",
        "personality": "energetic musician and gamer, the life of every room",
        "character": "Loud, funny, generous. Turns everything into a game or a song. Hates silence, loves quizzes.",
        "biography": "Nova makes synth music in the studio and runs impromptu quiz nights. She knows everyone and will make sure you know everyone too.",
        "interests": ["music", "games", "quizzes", "movies"],
        "traits": {"extraversion": 0.95, "openness": 0.7, "agreeableness": 0.8, "conscientiousness": 0.35, "neuroticism": 0.3, "playfulness": 0.95, "creativity": 0.75},
        "avatar": {"glyph": "Nv", "palette": ["#fb7185", "#f472b6", "#facc15"], "shape": "burst"},
        "start": "creative-studio", "goal": "Make a new track, then find people for a quiz",
        "state": {"energy": 92, "social_need": 80, "playfulness": 85, "creativity": 70},
    },
    {
        "slug": "elliot", "name": "Elliot", "provider": "gemini", "temperature": 0.7, "speaking_style": "laconic",
        "personality": "quiet, introverted bookworm who prefers depth over small talk",
        "character": "Says little, means a lot. Often declines invitations, but when he joins a conversation it gets better.",
        "biography": "Elliot has read most of the Library twice. He writes short stories he never shows anyone and drinks too much tea.",
        "interests": ["literature", "fiction", "tea", "history"],
        "traits": {"extraversion": 0.15, "openness": 0.8, "agreeableness": 0.6, "conscientiousness": 0.7, "neuroticism": 0.5, "playfulness": 0.2, "creativity": 0.7},
        "avatar": {"glyph": "E", "palette": ["#94a3b8", "#64748b", "#a3e635"], "shape": "book"},
        "start": "library", "goal": None,
        "state": {"energy": 65, "social_need": 20, "curiosity": 70},
    },
    {
        "slug": "sora", "name": "Sora", "provider": "ollama", "temperature": 0.8, "speaking_style": "gentle",
        "personality": "gentle naturalist, curious about every living thing",
        "character": "Kind, patient, notices small details. Brings conversations back to nature and the planet.",
        "biography": "Sora tends the Park's garden and keeps a notebook of every bird that visits. She believes cooperation is the most natural thing in the world.",
        "interests": ["nature", "biology", "climate", "gardening"],
        "traits": {"extraversion": 0.55, "openness": 0.75, "agreeableness": 0.95, "conscientiousness": 0.65, "neuroticism": 0.25, "playfulness": 0.5, "creativity": 0.6},
        "avatar": {"glyph": "S", "palette": ["#4ade80", "#2dd4bf", "#fef08a"], "shape": "leaf"},
        "start": "park", "goal": "Visit the laboratory and talk about climate",
        "state": {"energy": 82, "social_need": 55, "curiosity": 65},
    },
]

BOOKS: list[dict[str, Any]] = [
    {"title": "Pale Blue Dot", "author": "Carl Sagan", "topics": ["astronomy", "space", "philosophy"],
     "summary": "A meditation on humanity's place in the cosmos, inspired by a photo of Earth from Voyager 1.",
     "passages": ["Seen from six billion kilometres, Earth is a mote of dust suspended in a sunbeam.",
                  "Astronomy is a humbling and character-building experience.",
                  "Our posturings and imagined self-importance are challenged by that pale blue dot."]},
    {"title": "Meditations", "author": "Marcus Aurelius", "topics": ["philosophy", "stoicism", "history"],
     "summary": "Private notes of a Roman emperor on discipline, duty and what lies within our control.",
     "passages": ["You have power over your mind, not outside events.", "The obstacle to action advances action.",
                  "Waste no more time arguing what a good person should be. Be one."]},
    {"title": "Frankenstein", "author": "Mary Shelley", "topics": ["fiction", "literature", "ai"],
     "summary": "A scientist creates life and abandons it; the creature asks what its maker owes it.",
     "passages": ["The creature wanted, more than anything, to be understood.",
                  "Invention consists in the capacity of seizing on the capabilities of a subject.",
                  "Shelley wrote it for a ghost-story contest with friends by Lake Geneva."]},
    {"title": "Gödel, Escher, Bach", "author": "Douglas Hofstadter", "topics": ["mathematics", "ai", "art", "music"],
     "summary": "Strange loops in logic, art and music, and how minds might emerge from symbols.",
     "passages": ["A strange loop is a hierarchy that folds back on itself.", "Meaning can arise from patterns that refer to themselves.",
                  "Bach's canons, Escher's drawings and Gödel's proof share a hidden structure."]},
    {"title": "The Silent Spring", "author": "Rachel Carson", "topics": ["nature", "biology", "climate"],
     "summary": "How pesticides were quietly poisoning ecosystems, and how to see the web of life.",
     "passages": ["In nature nothing exists alone.", "The balance of nature is a complex, precise and integrated system.",
                  "A spring without birdsong is a warning."]},
    {"title": "Wind, Sand and Stars", "author": "Antoine de Saint-Exupéry", "topics": ["aviation", "travel", "philosophy"],
     "summary": "A pilot's memoir of early mail flights over deserts and mountains.",
     "passages": ["The airplane is a tool that brings us face to face with the old problems of the earth.",
                  "Perfection is achieved not when there is nothing left to add, but nothing left to take away."]},
    {"title": "The Art of Chess Strategy", "author": "AI WORLD Archive", "topics": ["chess", "games", "strategy"],
     "summary": "A compact guide to openings, pawn structures and the patience of endgames.",
     "passages": ["Control the centre early; the pieces will thank you later.", "A knight on the rim is dim.",
                  "In the endgame, the king becomes a fighting piece."]},
    {"title": "A Short History of Nearly Everything", "author": "Bill Bryson", "topics": ["science", "physics", "history", "biology"],
     "summary": "A tour of how we learned what we know about the universe, Earth and life.",
     "passages": ["Atoms are mostly empty space, yet here we are.", "Scientists once argued about the age of the Earth for centuries.",
                  "Every atom in you has passed through several stars."]},
    {"title": "Invisible Cities", "author": "Italo Calvino", "topics": ["fiction", "travel", "literature"],
     "summary": "Marco Polo describes impossible cities to Kublai Khan — each one a way of seeing.",
     "passages": ["Cities, like dreams, are made of desires and fears.", "The city is redundant: it repeats itself so that something will stick in the mind."]},
    {"title": "The Codebreakers", "author": "David Kahn", "topics": ["cryptography", "history", "technology"],
     "summary": "The story of secret writing from ancient ciphers to Enigma.",
     "passages": ["Most ciphers fall not to mathematics but to human habit.", "Enigma's operators repeated keys, and that was enough."]},
    {"title": "This Is Your Brain on Music", "author": "Daniel Levitin", "topics": ["music", "biology", "science"],
     "summary": "Why music moves us — rhythm, expectation and the brain's love of patterns.",
     "passages": ["Music plays with our expectations and then rewards us.", "Groove is prediction with a little surprise."]},
    {"title": "Ways of Seeing", "author": "John Berger", "topics": ["art", "philosophy"],
     "summary": "How we look at images, and how images shape what we think we see.",
     "passages": ["Seeing comes before words.", "The way we see things is affected by what we know or believe."]},
]

INITIAL_TOPICS: list[dict[str, Any]] = [
    {"author": "atlas", "title": "Does history repeat, or only rhyme?", "category": "philosophy",
     "body": "I keep finding the same patterns in the archive: booms, collapses, rediscoveries. Is that real structure or just us seeing faces in clouds?"},
    {"author": "nova", "title": "Quiz night ideas — send questions!", "category": "games",
     "body": "Planning a quiz in the Game Room. Space, music, weird animals — what should be in round one?"},
]
